# Generated by Django 6.0 on 2026-01-08 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='session_id',
            field=models.CharField(default='default', max_length=100),
            preserve_default=False,
        ),
    ]
